# Generated by Django 4.0.8 on 2024-04-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='image', upload_to='static/blog/% Y/% m/% d/', verbose_name='Image'),
        ),
    ]
