# Generated by Django 4.0.8 on 2024-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='media/blog/%Y/%m/%D/', verbose_name='Image'),
        ),
    ]
